// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ServiceProto.proto
#ifndef GRPC_ServiceProto_2eproto__INCLUDED
#define GRPC_ServiceProto_2eproto__INCLUDED

#include "ServiceProto.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ServiceNetIO {

class UserServiceInterface final {
 public:
  static constexpr char const* service_full_name() {
    return "ServiceNetIO.UserServiceInterface";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>> NewNotify(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>>(NewNotifyRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>> AsyncNewNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>>(AsyncNewNotifyRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>> PrepareAsyncNewNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>>(PrepareAsyncNewNotifyRaw(context, cq));
    }
    // rpc GetNames (GetNamesRequest) returns (GetNamesResponse);
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void NewNotify(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ServiceNetIO::NewMessageRequest,::ServiceNetIO::ServiceMessageResponse>* reactor) = 0;
      // rpc GetNames (GetNamesRequest) returns (GetNamesResponse);
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* NewNotifyRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* AsyncNewNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* PrepareAsyncNewNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>> NewNotify(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>>(NewNotifyRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>> AsyncNewNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>>(AsyncNewNotifyRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>> PrepareAsyncNewNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>>(PrepareAsyncNewNotifyRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void NewNotify(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ServiceNetIO::NewMessageRequest,::ServiceNetIO::ServiceMessageResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* NewNotifyRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* AsyncNewNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* PrepareAsyncNewNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NewNotify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status NewNotify(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* stream);
    // rpc GetNames (GetNamesRequest) returns (GetNamesResponse);
  };
  template <class BaseClass>
  class WithAsyncMethod_NewNotify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NewNotify() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NewNotify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewNotify(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewNotify(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NewNotify<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_NewNotify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_NewNotify() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->NewNotify(context); }));
    }
    ~WithCallbackMethod_NewNotify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewNotify(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* NewNotify(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_NewNotify<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NewNotify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NewNotify() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NewNotify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewNotify(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NewNotify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NewNotify() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NewNotify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewNotify(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewNotify(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_NewNotify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_NewNotify() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->NewNotify(context); }));
    }
    ~WithRawCallbackMethod_NewNotify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewNotify(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* NewNotify(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};
// 服务名

}  // namespace ServiceNetIO


#endif  // GRPC_ServiceProto_2eproto__INCLUDED
