// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ServiceProto.proto

#include "ServiceProto.pb.h"
#include "ServiceProto.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ServiceNetIO {

static const char* UserServiceInterface_method_names[] = {
  "/ServiceNetIO.UserServiceInterface/NewNotify",
};

std::unique_ptr< UserServiceInterface::Stub> UserServiceInterface::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserServiceInterface::Stub> stub(new UserServiceInterface::Stub(channel, options));
  return stub;
}

UserServiceInterface::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_NewNotify_(UserServiceInterface_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* UserServiceInterface::Stub::NewNotifyRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>::Create(channel_.get(), rpcmethod_NewNotify_, context);
}

void UserServiceInterface::Stub::async::NewNotify(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ServiceNetIO::NewMessageRequest,::ServiceNetIO::ServiceMessageResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ServiceNetIO::NewMessageRequest,::ServiceNetIO::ServiceMessageResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_NewNotify_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* UserServiceInterface::Stub::AsyncNewNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>::Create(channel_.get(), cq, rpcmethod_NewNotify_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>* UserServiceInterface::Stub::PrepareAsyncNewNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>::Create(channel_.get(), cq, rpcmethod_NewNotify_, context, false, nullptr);
}

UserServiceInterface::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServiceInterface_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< UserServiceInterface::Service, ::ServiceNetIO::NewMessageRequest, ::ServiceNetIO::ServiceMessageResponse>(
          [](UserServiceInterface::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ServiceNetIO::ServiceMessageResponse,
             ::ServiceNetIO::NewMessageRequest>* stream) {
               return service->NewNotify(ctx, stream);
             }, this)));
}

UserServiceInterface::Service::~Service() {
}

::grpc::Status UserServiceInterface::Service::NewNotify(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ServiceNetIO::ServiceMessageResponse, ::ServiceNetIO::NewMessageRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ServiceNetIO

